### ISSUE TITLE
Beets plugin not working on python 3.8

### ISSUE THREAD

**Issue by dioio-io** [YetAnotherNerd/whatlastgenre#24]
After having my beets image upgraded to a more recent version of python, this plugin stopped working

```python3 /config/whatlastgenre-master/plugin/beets/beetsplug/wlg.py```

```
Traceback (most recent call last):
  File "/config/whatlastgenre-master/plugin/beets/beetsplug/wlg.py", line 28, in <module>
    from wlg import whatlastgenre
  File "/config/whatlastgenre-master/plugin/beets/beetsplug/wlg.py", line 28, in <module>
    from wlg import whatlastgenre
ImportError: cannot import name 'whatlastgenre' from partially initialized module 'wlg' (most likely due to a circular import) (/config/whatlastgenre-master/plugin/beets/beetsplug/wlg.py)
```

---
beets version 1.4.9
Python version 3.8.2

**Comment by dioio-io** [comment]
Nevermind, I needed to re-install ./whatlastgenre/setup.py
